apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue-deployment
  labels:
    app: messaging-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app-blue
  template:
    metadata:
      labels:
        app: messaging-app-blue
    spec:
      containers:
      - name: messaging-app
        image: my-django-app:latest # Replace with your actual Docker image name
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
