apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue-deployment
  labels:
    app: messaging-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app-blue
  template:
    metadata:
      labels:
        app: messaging-app-blue
    spec:
      containers:
      - name: messaging-app
        image: my-django-app:2.0 # Updated version for rolling update
        ports:
        - containerPort: 8000
